site_name: Web-программирование

nav:
  - Главная: index.md
  - Лабораторные работы:
      - Лабораторная работа 1:
          - Лабораторная: lab1
          - Практика 1: practice1.1
          - Практика 2: practice1.2
          - Практика 3: practice1.3

theme:
  name: material
